addons:
  ssh_known_hosts: gitlab.com
jobs:
  include:
  - os: osx
    osx_image: xcode11
    name: 'iOS Build'
    # https://github.com/travis-ci/travis-conditions/issues/13#issuecomment-414734455
    if:  1 != 1
    env:
    - TARGET_PLATFORM=ios
    - GPG=gpg
    - FASTLANE_SKIP_UPLOAD=true
  - &androidrelease
    name: 'Android Dev Build'
    os: linux
    language: android
    #if: branch = master
    # disabled for now, build via github actions.
    if: 1 != 1
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - android-28
        - android-29
        - build-tools-28.0.3
        - build-tools-29.0.2
      licenses:
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - '.+'
        - platforms;android-29
        - platforms;android-28
    before_install:
    #- sdkmanager --version
    - sudo apt-get install -y gnupg2
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "ndk;21.0.6113669"
    - yes | sdkmanager "ndk;20.0.5594570"
    - time yes | sdkmanager "platforms;android-28"
    - time yes | sdkmanager "platforms;android-29"
    # - time yes | sdkmanager --licenses
    - gem update --system
    - gem install fastlane --no-document --quiet
    env:
    - TARGET_PLATFORM=android
    - TARGET_VARIANT=playstoredev
    - GPG=gpg2
  - <<: *androidrelease
    name: 'Android Stable Build'
    if: branch = stable
    env:
    - TARGET_VARIANT=android
    - GPG=gpg2
before_install:
#- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
#  -in .travis_sec/BLACKBOX_KEY.txt.enc -out .travis_sec/BLACKBOX_KEY.txt -d
- which gpg
- which gpg2 || echo "gpg2 not found."
- gpg --version
- echo Test
install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in .travis_sec/BLACKBOX_KEY.txt.enc -out .travis_sec/BLACKBOX_KEY.txt -d
- "$GPG -v --import < .travis_sec/BLACKBOX_KEY.txt"
- "./authpass/_tools/ci-install-deps.sh ${TARGET_PLATFORM}"
script:
- "./authpass/_tools/ci-release.sh ${TARGET_PLATFORM} ${TARGET_VARIANT:-$TARGET_PLATFORM}"
