blank_issues_enabled: true
contact_links:
  - name: AuthPass User Forum
    url: https://forum.authpass.app/
    about: Please ask and answer questions here.
  - name: AuthPass Feature Suggestions & Discussions
    url: https://forum.authpass.app/c/feature-discussions/7
    about: Please suggestion features here, so they can be discussed and voted.
